export const DAILY_WISDOM_NOTIFICATION_HOUR = 9;
export const DAILY_WISDOM_NOTIFICATION_MINUTE = 0;
export const DAILY_WISDOM_NOTIFICATION_TIME = '09:00';
export const DAILY_WISDOM_NOTIFICATION_TIME_LABEL = '9:00 AM';

export const FESTIVAL_NOTIFICATION_HOUR = 12;
export const FESTIVAL_NOTIFICATION_MINUTE = 0;
