-- Guide Glossary: reference data for the Gita Guide feature
-- Chapter themes use chapter_number to join with gita_chapters for real chapter names

CREATE TABLE IF NOT EXISTS gita_guide_glossary (
  id              serial       PRIMARY KEY,
  category        text         NOT NULL,
  category_label  text         NOT NULL,
  category_order  integer      NOT NULL DEFAULT 0,
  term            text,
  meaning         text         NOT NULL,
  chapter_number  integer,
  sort_order      integer      NOT NULL DEFAULT 0
);

ALTER TABLE gita_guide_glossary ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read guide glossary" ON gita_guide_glossary;
CREATE POLICY "Anyone can read guide glossary"
  ON gita_guide_glossary FOR SELECT
  USING (true);

-- ────────────────────────────────────────────────────────────
-- DATA
-- ────────────────────────────────────────────────────────────

INSERT INTO gita_guide_glossary
  (category, category_label, category_order, term, meaning, chapter_number, sort_order)
VALUES

-- ── Main People ──────────────────────────────────────────────
('main_people','Main People',1,'Krishna',
 'Arjuna''s charioteer, friend, guide, and the divine teacher of the Bhagavad Gita.',
 NULL,1),
('main_people','Main People',1,'Arjuna',
 'A Pandava warrior prince who becomes confused and sorrowful before battle. His questions lead to Krishna''s teachings.',
 NULL,2),
('main_people','Main People',1,'Dhritarashtra',
 'The blind king of Hastinapura and father of the Kauravas. The Gita begins with him asking Sanjaya what happened on the battlefield.',
 NULL,3),
('main_people','Main People',1,'Sanjaya',
 'Dhritarashtra''s advisor who narrates the events of the battlefield through divine vision.',
 NULL,4),
('main_people','Main People',1,'Pandavas',
 'The five brothers on the side of dharma: Yudhishthira, Bhima, Arjuna, Nakula, and Sahadeva.',
 NULL,5),
('main_people','Main People',1,'Kauravas',
 'The opposing side, led by Duryodhana. They fight against the Pandavas.',
 NULL,6),
('main_people','Main People',1,'Duryodhana',
 'The eldest Kaurava prince who refuses to give the Pandavas their rightful kingdom.',
 NULL,7),
('main_people','Main People',1,'Bhishma',
 'A respected elder warrior who fights on the Kaurava side because of his duty and vows.',
 NULL,8),
('main_people','Main People',1,'Drona',
 'Arjuna''s teacher in warfare who also fights on the Kaurava side.',
 NULL,9),
('main_people','Main People',1,'Karna',
 'A powerful warrior allied with Duryodhana and a major rival of Arjuna.',
 NULL,10),
('main_people','Main People',1,'Vyasa',
 'The sage who composed the Mahabharata, the larger epic that contains the Bhagavad Gita.',
 NULL,11),

-- ── Places & Setting ─────────────────────────────────────────
('places_setting','Places & Setting',2,'Kurukshetra',
 'The battlefield where the Bhagavad Gita is spoken.',
 NULL,1),
('places_setting','Places & Setting',2,'Dharma-kshetra',
 '"Field of dharma." This shows the battle has moral and spiritual importance.',
 NULL,2),
('places_setting','Places & Setting',2,'Hastinapura',
 'The kingdom at the center of the conflict between the Pandavas and Kauravas.',
 NULL,3),

-- ── Core Spiritual Terms ──────────────────────────────────────
('spiritual_terms','Core Spiritual Terms',3,'Dharma',
 'Duty, righteousness, moral order, and the right way to live.',
 NULL,1),
('spiritual_terms','Core Spiritual Terms',3,'Karma',
 'Action and the results created by action.',
 NULL,2),
('spiritual_terms','Core Spiritual Terms',3,'Atman',
 'The true self or soul, which is eternal and different from the body.',
 NULL,3),
('spiritual_terms','Core Spiritual Terms',3,'Brahman',
 'The ultimate reality behind everything.',
 NULL,4),
('spiritual_terms','Core Spiritual Terms',3,'Paramatman',
 'The Supreme Self, or God within all beings.',
 NULL,5),
('spiritual_terms','Core Spiritual Terms',3,'Moksha',
 'Liberation from the cycle of birth and death.',
 NULL,6),
('spiritual_terms','Core Spiritual Terms',3,'Samsara',
 'The cycle of birth, death, and rebirth.',
 NULL,7),
('spiritual_terms','Core Spiritual Terms',3,'Maya',
 'Divine illusion, or the power that makes temporary things seem permanent.',
 NULL,8),
('spiritual_terms','Core Spiritual Terms',3,'Jnana',
 'Spiritual knowledge or wisdom.',
 NULL,9),
('spiritual_terms','Core Spiritual Terms',3,'Bhakti',
 'Devotion and loving surrender to God.',
 NULL,10),
('spiritual_terms','Core Spiritual Terms',3,'Vairagya',
 'Detachment from worldly desires and results.',
 NULL,11),
('spiritual_terms','Core Spiritual Terms',3,'Tyaga',
 'Renunciation, especially giving up attachment to the results of action.',
 NULL,12),
('spiritual_terms','Core Spiritual Terms',3,'Sannyasa',
 'Renunciation. In the Gita, true renunciation means giving up selfish attachment, not simply avoiding action.',
 NULL,13),
('spiritual_terms','Core Spiritual Terms',3,'Shraddha',
 'Faith, trust, sincerity, and spiritual confidence.',
 NULL,14),
('spiritual_terms','Core Spiritual Terms',3,'Tapas',
 'Discipline, austerity, or spiritual effort.',
 NULL,15),
('spiritual_terms','Core Spiritual Terms',3,'Yajna',
 'Sacrifice, offering, or sacred action done for a higher purpose.',
 NULL,16),
('spiritual_terms','Core Spiritual Terms',3,'Dana',
 'Charity or giving.',
 NULL,17),
('spiritual_terms','Core Spiritual Terms',3,'Ahimsa',
 'Nonviolence and not harming others.',
 NULL,18),
('spiritual_terms','Core Spiritual Terms',3,'Satya',
 'Truthfulness.',
 NULL,19),
('spiritual_terms','Core Spiritual Terms',3,'Shanti',
 'Peace.',
 NULL,20),
('spiritual_terms','Core Spiritual Terms',3,'Ananda',
 'Bliss or spiritual joy.',
 NULL,21),

-- ── The Three Gunas ───────────────────────────────────────────
('three_gunas','The Three Gunas',4,'Sattva',
 'Purity, clarity, wisdom, peace, and balance.',
 NULL,1),
('three_gunas','The Three Gunas',4,'Rajas',
 'Passion, desire, restlessness, ambition, and attachment.',
 NULL,2),
('three_gunas','The Three Gunas',4,'Tamas',
 'Darkness, ignorance, laziness, confusion, and dullness.',
 NULL,3),
('three_gunas','The Three Gunas',4,'Triguna',
 'The three gunas together: sattva, rajas, and tamas.',
 NULL,4),
('three_gunas','The Three Gunas',4,'Guna-atita',
 'One who has gone beyond the control of the three gunas.',
 NULL,5),

-- ── Types of Yoga ─────────────────────────────────────────────
('types_of_yoga','Types of Yoga',5,'Karma Yoga',
 'The path of selfless action.',
 NULL,1),
('types_of_yoga','Types of Yoga',5,'Jnana Yoga',
 'The path of spiritual knowledge and wisdom.',
 NULL,2),
('types_of_yoga','Types of Yoga',5,'Bhakti Yoga',
 'The path of devotion and loving surrender to Krishna.',
 NULL,3),
('types_of_yoga','Types of Yoga',5,'Dhyana Yoga',
 'The path of meditation and controlling the mind.',
 NULL,4),
('types_of_yoga','Types of Yoga',5,'Sankhya Yoga',
 'The path of wisdom that separates the soul from the body and material world.',
 NULL,5),
('types_of_yoga','Types of Yoga',5,'Buddhi Yoga',
 'The yoga of disciplined intelligence and acting with spiritual understanding.',
 NULL,6),
('types_of_yoga','Types of Yoga',5,'Abhyasa Yoga',
 'The yoga of repeated practice and training the mind.',
 NULL,7),
('types_of_yoga','Types of Yoga',5,'Sannyasa Yoga',
 'The yoga of renunciation, giving up ego and attachment.',
 NULL,8),

-- ── Philosophical Concepts ────────────────────────────────────
('philosophical_concepts','Philosophical Concepts',6,'Prakriti',
 'Material nature, including the body, mind, senses, and physical world.',
 NULL,1),
('philosophical_concepts','Philosophical Concepts',6,'Purusha',
 'The conscious self or spirit. In some contexts, it can also refer to the Supreme Person.',
 NULL,2),
('philosophical_concepts','Philosophical Concepts',6,'Kshetra',
 'The "field," meaning the body and material experience.',
 NULL,3),
('philosophical_concepts','Philosophical Concepts',6,'Kshetrajna',
 'The "knower of the field," meaning the soul who experiences the body.',
 NULL,4),
('philosophical_concepts','Philosophical Concepts',6,'Avidya',
 'Ignorance, especially ignorance of the true self.',
 NULL,5),
('philosophical_concepts','Philosophical Concepts',6,'Vidya',
 'True knowledge or spiritual wisdom.',
 NULL,6),
('philosophical_concepts','Philosophical Concepts',6,'Buddhi',
 'Intellect, understanding, or spiritual intelligence.',
 NULL,7),
('philosophical_concepts','Philosophical Concepts',6,'Manas',
 'The mind, especially the part that thinks, feels, and reacts.',
 NULL,8),
('philosophical_concepts','Philosophical Concepts',6,'Indriyas',
 'The senses.',
 NULL,9),
('philosophical_concepts','Philosophical Concepts',6,'Ahamkara',
 'Ego, or the false idea that "I am this body" or "I am the doer."',
 NULL,10),
('philosophical_concepts','Philosophical Concepts',6,'Kama',
 'Desire or selfish craving.',
 NULL,11),
('philosophical_concepts','Philosophical Concepts',6,'Krodha',
 'Anger.',
 NULL,12),
('philosophical_concepts','Philosophical Concepts',6,'Lobha',
 'Greed.',
 NULL,13),
('philosophical_concepts','Philosophical Concepts',6,'Moha',
 'Delusion or confusion.',
 NULL,14),
('philosophical_concepts','Philosophical Concepts',6,'Mada',
 'Pride or arrogance.',
 NULL,15),
('philosophical_concepts','Philosophical Concepts',6,'Matsarya',
 'Jealousy or envy.',
 NULL,16),
('philosophical_concepts','Philosophical Concepts',6,'Samatvam',
 'Even-mindedness and balance in success and failure.',
 NULL,17),
('philosophical_concepts','Philosophical Concepts',6,'Sthita-prajna',
 'A person of steady wisdom who is not shaken by pleasure, pain, gain, or loss.',
 NULL,18),
('philosophical_concepts','Philosophical Concepts',6,'Nishkama Karma',
 'Action done without selfish desire for the result.',
 NULL,19),
('philosophical_concepts','Philosophical Concepts',6,'Svadharma',
 'One''s own duty based on nature, role, and responsibility.',
 NULL,20),
('philosophical_concepts','Philosophical Concepts',6,'Paradharma',
 'Another person''s duty.',
 NULL,21),
('philosophical_concepts','Philosophical Concepts',6,'Loka-sangraha',
 'Acting for the welfare and order of the world.',
 NULL,22),
('philosophical_concepts','Philosophical Concepts',6,'Ishvara',
 'The Lord, God, or Supreme Controller.',
 NULL,23),
('philosophical_concepts','Philosophical Concepts',6,'Avatara',
 'A divine descent, when God appears to restore dharma.',
 NULL,24),
('philosophical_concepts','Philosophical Concepts',6,'Adharma',
 'Unrighteousness, injustice, or action against dharma.',
 NULL,25),
('philosophical_concepts','Philosophical Concepts',6,'Daivi Sampad',
 'Divine qualities such as fearlessness, purity, compassion, and truthfulness.',
 NULL,26),
('philosophical_concepts','Philosophical Concepts',6,'Asuri Sampad',
 'Destructive qualities such as arrogance, anger, harshness, and ignorance.',
 NULL,27),
('philosophical_concepts','Philosophical Concepts',6,'Yukta',
 'One who is disciplined, balanced, or united in yoga.',
 NULL,28),
('philosophical_concepts','Philosophical Concepts',6,'Ayukta',
 'One who is undisciplined or disconnected from spiritual wisdom.',
 NULL,29),

-- ── Names Krishna Uses for Arjuna ────────────────────────────
('krishna_names_for_arjuna','Names Krishna Uses for Arjuna',7,'Bharata',
 'Refers to Arjuna. Krishna uses Bharata to remind Arjuna that he comes from the great Bharata lineage and should act with courage and dharma.',
 NULL,1),

-- ── Names Sanjaya Uses ────────────────────────────────────────
('sanjaya_names','Names Sanjaya Uses',8,'Bhagavan',
 'Refers to Krishna.',
 NULL,1),
('sanjaya_names','Names Sanjaya Uses',8,'Hrishikesha',
 'Refers to Krishna.',
 NULL,2),
('sanjaya_names','Names Sanjaya Uses',8,'Pandava',
 'Refers to Arjuna.',
 NULL,3),
('sanjaya_names','Names Sanjaya Uses',8,'Dhananjaya',
 'Refers to Arjuna.',
 NULL,4),

-- ── Chapter Themes ────────────────────────────────────────────
-- term is NULL here; the chapter name is fetched live from gita_chapters
('chapter_themes','Chapter Themes',9,NULL,
 'Arjuna''s sorrow and confusion before the battle.',
 1,1),
('chapter_themes','Chapter Themes',9,NULL,
 'The eternal soul, wisdom, and acting with balance.',
 2,2),
('chapter_themes','Chapter Themes',9,NULL,
 'Selfless action and doing one''s duty.',
 3,3),
('chapter_themes','Chapter Themes',9,NULL,
 'Divine wisdom, action, sacrifice, and Krishna''s avatara teaching.',
 4,4),
('chapter_themes','Chapter Themes',9,NULL,
 'True renunciation and acting without attachment.',
 5,5),
('chapter_themes','Chapter Themes',9,NULL,
 'Meditation, discipline, and controlling the mind.',
 6,6),
('chapter_themes','Chapter Themes',9,NULL,
 'Knowing Krishna''s divine nature.',
 7,7),
('chapter_themes','Chapter Themes',9,NULL,
 'The imperishable Brahman and remembering God.',
 8,8),
('chapter_themes','Chapter Themes',9,NULL,
 'The royal knowledge and secret of devotion.',
 9,9),
('chapter_themes','Chapter Themes',9,NULL,
 'Krishna''s divine glories throughout creation.',
 10,10),
('chapter_themes','Chapter Themes',9,NULL,
 'Krishna reveals His universal form.',
 11,11),
('chapter_themes','Chapter Themes',9,NULL,
 'Devotion and the qualities of a true devotee.',
 12,12),
('chapter_themes','Chapter Themes',9,NULL,
 'The body as the field and the soul as the knower.',
 13,13),
('chapter_themes','Chapter Themes',9,NULL,
 'The three gunas: sattva, rajas, and tamas.',
 14,14),
('chapter_themes','Chapter Themes',9,NULL,
 'Krishna as the Supreme Person beyond the changing world.',
 15,15),
('chapter_themes','Chapter Themes',9,NULL,
 'Divine and destructive qualities.',
 16,16),
('chapter_themes','Chapter Themes',9,NULL,
 'Three kinds of faith, food, sacrifice, discipline, and charity.',
 17,17),
('chapter_themes','Chapter Themes',9,NULL,
 'Final summary of duty, renunciation, devotion, surrender, and liberation.',
 18,18);
